### ISSUE TITLE
[Solution] :compileKotlin task fails

### ISSUE THREAD

**Issue by techspider** [corda/djvm#27]
If Gradle fails to compile DJVM at task :compileKotlin, you must install OpenJDK 8 JDK on Linux and make it the default JDK on the system. I highly suggest uninstalling any other JDKs if they exist. I have also tried the Oracle JDK, however, it does not seem to be working properly from my testing.

This is a common issue that seems to plague some users when trying to build DJVM.

**Comment by chrisr3** [comment]
I assure you it _does_ compile because our TeamCity jobs would have noticed if it didn't :wink:. May I ask which JDK you were trying to use before installing OpenJDK 8 please?
